version: '3'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      PYTHONUNBUFFERED: 1
    command: "uvicorn app.app:app --reload --log-level debug --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
