AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: playground ab api securities

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "default"
        Parameters:
          - Env
Parameters:
  ###############################
  # 外部からのパラメーター
  ###############################
  Env:
    Type: String
    Description: 環境種別
  SystemName:
    Type: String
    Description: システム名
  ServiceName:
    Type: String
    Description: サービス名

  ###############################
  # パラメーター
  ###############################
  AlbSGName:
    Type: String
    Default: alb
  EcsSGName:
    Type: String
    Default: ecs
  EcsTaskExecRoleName:
    Type: String
    Default: ecs-task-exec
  AutoScalingRoleName:
    Type: String
    Default: auto-scaling
  AutoScalingPolicyName:
    Type: String
    Default: auto-scaling
  ScaleOutPolicyName:
    Type: String
    Default: scale-out
  ScaleInPolicyName:
    Type: String
    Default: scale-in

###############################
# リソース
###############################
Resources:
  ###############################
  # SecurityGroup
  ###############################
  ### AlbSG ###
  AlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${SystemName}-${ServiceName}-${AlbSGName}-${Env}
      GroupDescription: api alb
      SecurityGroupIngress:
        - IpProtocol: -1
      VpcId:
        Fn::ImportValue: !Sub ${SystemName}-vpc-id
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${ServiceName}-${AlbSGName}-${Env}
        - Key: System
          Value: !Ref SystemName
        - Key: Env
          Value: !Ref Env

  ### EcsSG ###
  EcsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${SystemName}-${ServiceName}-${EcsSGName}-${Env}
      GroupDescription: api ecs
      SecurityGroupIngress:
        - IpProtocol: -1
      VpcId:
        Fn::ImportValue: !Sub ${SystemName}-vpc-id
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${ServiceName}-${EcsSGName}-${Env}
        - Key: System
          Value: !Ref SystemName
        - Key: Env
          Value: !Ref Env

  ###############################
  # Role
  ###############################
  ### EcsTaskExecutionRole ###
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${ServiceName}-${EcsTaskExecRoleName}-${Env}
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ### ServiceAutoScalingRole ###
  ServiceAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${ServiceName}-${AutoScalingRoleName}-${Env}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${SystemName}-${ServiceName}-${AutoScalingPolicyName}-${Env}
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - application-autoscaling:*
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricAlarm
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource: '*'

###############################
# 出力
###############################
Outputs:
  AlbSGId:
    Value: !Ref AlbSG
    Export:
      Name: !Sub ${SystemName}-${ServiceName}-${AlbSGName}-id
  EcsSGId:
    Value: !Ref EcsSG
    Export:
      Name: !Sub ${SystemName}-${ServiceName}-${EcsSGName}-id
  EcsTaskExecutionRoleArn:
    Value: !GetAtt EcsTaskExecutionRole.Arn
    Export:
      Name: !Sub ${SystemName}-${ServiceName}-${EcsTaskExecRoleName}-arn
  ServiceAutoScalingRoleArn:
    Value: !GetAtt ServiceAutoScalingRole.Arn
    Export:
      Name: !Sub ${SystemName}-${ServiceName}-${AutoScalingRoleName}-arn
