AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: playground ab api securities

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "default"
        Parameters:
          - Env
Parameters:
  ###############################
  # 外部からのパラメーター
  ###############################
  Env:
    Type: String
    Description: 環境種別
  SystemName:
    Type: String
    Description: システム名
  ServiceName:
    Type: String
    Description: サービス名

  ###############################
  # パラメーター
  ###############################
  AlbSGName:
    Type: String
    Default: alb
  FargateSGName:
    Type: String
    Default: fargate
  FargateTaskExecRoleName:
    Type: String
    Default: fargate-task-exec
  AutoScalingRoleName:
    Type: String
    Default: auto-scaling
  ScaleOutPolicyName:
    Type: String
    Default: scale-out
  ScaleInPolicyName:
    Type: String
    Default: scale-in

###############################
# リソース
###############################
Resources:
  ###############################
  # SecurityGroup
  ###############################
  ### AlbSG ###
  AlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${SystemName}-${ServiceName}-${AlbSGName}-${Env}
      GroupDescription: api alb
      SecurityGroupIngress:
        - IpProtocol: -1
      VpcId:
        Fn::ImportValue: !Sub ${SystemName}-vpc-id
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${ServiceName}-${AlbSGName}-${Env}
        - Key: System
          Value: !Ref SystemName
        - Key: Env
          Value: !Ref Env

  ### SecurityGroup2 ###
  SecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !FindInMap ${SystemName}-${ServiceName}-${FargateSGName}-${Env}
      GroupDescription: api fargate
      SecurityGroupIngress:
        - IpProtocol: -1
      VpcId: !FindInMap [Vpc, VpcId1, !Ref Env]
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${ServiceName}-${FargateSGName}-${Env}
        - Key: System
          Value: !Ref SystemName
        - Key: Env
          Value: !Ref Env